const S={caps:[],cert:[],aval:[],tab:'geral',year:'',cat:'',vinc:'',q:'',nameQ:'',procQ:''}; const charts={};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)]; const fmt=n=>new Intl.NumberFormat('pt-BR').format(n||0); const norm=s=>(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
Promise.all(['dados/capacitacoes.json','dados/certificados.json','dados/avaliacao.json'].map(u=>fetch(u).then(r=>{if(!r.ok)throw Error(u);return r.json()}))).then(([c,ce,a])=>{S.caps=c.registros;S.cert=ce.registros;S.aval=a.registros;init()}).catch(e=>{$('#notice').textContent='Erro ao carregar os dados. Abra a aplicação por um servidor/GitHub Pages, não diretamente pelo arquivo local.';console.error(e)});
function init(){const years=[...new Set([...S.caps.map(x=>x.a),...S.cert.map(x=>x.a),...S.aval.map(x=>x.ano)].filter(Boolean))].sort(); $('#years').innerHTML='<button data-y="" class="active">Todos</button>'+years.map(y=>`<button data-y="${y}">${y}</button>`).join(''); const cats=[...new Set(S.caps.map(x=>x.g).filter(Boolean))].sort(); $('#cat').innerHTML='<option value="">Todos</option>'+cats.map(x=>`<option>${esc(x)}</option>`).join(''); const vs=[...new Set([...S.caps.map(x=>x.v),...S.cert.map(x=>x.v)].filter(Boolean))].sort(); $('#vinc').innerHTML='<option value="">Todos</option>'+vs.map(x=>`<option>${esc(x)}</option>`).join(''); bind();render()}
function bind(){$$('.tab').forEach(b=>b.onclick=()=>{S.tab=b.dataset.tab;$$('.tab,.page').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+S.tab).classList.add('active');render()});$('#years').onclick=e=>{if(e.target.dataset.y!==undefined){S.year=e.target.dataset.y;$$('#years button').forEach(b=>b.classList.toggle('active',b.dataset.y===S.year));render()}};[['cat','cat'],['vinc','vinc']].forEach(([id,k])=>$('#'+id).onchange=e=>{S[k]=e.target.value;render()});[['q','q'],['nameQ','nameQ'],['procQ','procQ']].forEach(([id,k])=>$('#'+id).oninput=e=>{S[k]=e.target.value;render()});$('#clear').onclick=()=>{S.year=S.cat=S.vinc=S.q=S.nameQ=S.procQ='';['cat','vinc','q','nameQ','procQ'].forEach(id=>$('#'+id).value='');$$('#years button').forEach(b=>b.classList.toggle('active',b.dataset.y===''));render()};$('#btnPng').onclick=png;$('#btnXlsx').onclick=xlsx}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function fc(){let q=norm(S.q),nq=norm(S.nameQ),pq=norm(S.procQ);return S.caps.filter(x=>(!S.year||String(x.a)===S.year)&&(!S.cat||x.g===S.cat)&&(!S.vinc||x.v===S.vinc)&&(!q||norm(x.c).includes(q))&&(!nq||norm(x.n).includes(nq))&&(!pq||norm(x.s).includes(pq)))}
function fcert(){let nq=norm(S.nameQ);return S.cert.filter(x=>(!S.year||String(x.a)===S.year)&&(!S.vinc||x.v===S.vinc)&&(!nq||norm(x.n).includes(nq)))}
function fav(){let q=norm(S.q);return S.aval.filter(x=>(!S.year||String(x.ano)===S.year)&&(!q||norm(x.capacitacao).includes(q)))}
function uniq(a,key){return new Set(a.map(key).filter(Boolean)).size} function count(a,key){let m={};a.forEach(x=>{let k=key(x)||'Não informado';m[k]=(m[k]||0)+1});return m}
function chart(id,type,labels,data,label){if(charts[id])charts[id].destroy();charts[id]=new Chart($(id),{type,data:{labels,datasets:[{label,data}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:type==='doughnut'}}}})}
function render(){let c=fc(),ce=fcert(),a=fav(); let courses=uniq(c,x=>`${x.a}|${norm(x.c)}`), people=uniq(c,x=>norm(x.n)); ['kCursos','cCursos'].forEach(id=>$('#'+id).textContent=fmt(courses));['kPart','cPart'].forEach(id=>$('#'+id).textContent=fmt(c.length));['kPessoas','cPessoas'].forEach(id=>$('#'+id).textContent=fmt(people));['kCert','cCert'].forEach(id=>$('#'+id).textContent=fmt(ce.length));$('#kAval').textContent=fmt(a.length); if(S.tab==='geral')renderGeneral(c,ce); if(S.tab==='cursos')renderCourses(c,ce); if(S.tab==='avaliacao')renderAval(a)}
function renderGeneral(c,ce){let m=count(c,x=>x.a), cats=count(c,x=>x.g), v={};c.forEach(x=>{if(!v[x.v])v[x.v]=new Set();if(x.n)v[x.v].add(norm(x.n))});let cm=count(ce,x=>x.a);chart('#chAno','bar',Object.keys(m).sort(),Object.keys(m).sort().map(k=>m[k]),'Participações');chart('#chCat','doughnut',Object.keys(cats),Object.values(cats),'Participações');chart('#chVinc','bar',Object.keys(v),Object.values(v).map(s=>s.size),'Participantes');chart('#chCert','bar',Object.keys(cm).sort(),Object.keys(cm).sort().map(k=>cm[k]),'Certificados')}
function renderCourses(c,ce){let rows=[...c].sort((a,b)=>(b.d||'').localeCompare(a.d||'')||a.n.localeCompare(b.n));$('#partRows').innerHTML=rows.slice(0,1000).map(x=>`<tr><td>${esc(x.n)}</td><td>${esc(x.c)}</td><td>${esc(x.dt)}</td><td>${x.a||''}</td><td>${esc(x.g)}</td><td>${esc(x.cat)}</td><td>${esc(x.v)}</td><td>${esc(x.i)}</td><td>${esc(x.s)}</td></tr>`).join('');$('#partCount').textContent=`${fmt(rows.length)} participações encontradas${rows.length>1000?' · exibindo as 1.000 primeiras; o Excel contém todas':''}.`;let cr=[...ce].sort((a,b)=>(b.d||'').localeCompare(a.d||'')||a.n.localeCompare(b.n));$('#certRows').innerHTML=cr.slice(0,1000).map(x=>`<tr><td>${esc(x.n)}</td><td>${esc(x.dt)}</td><td>${x.a||''}</td><td>${esc(x.g)}</td><td>${esc(x.v)}</td><td>${esc(x.i)}</td><td class="code">${esc(x.cod)}</td></tr>`).join('');$('#certCount').textContent=`${fmt(cr.length)} certificados encontrados${cr.length>1000?' · exibindo os 1.000 primeiros; o Excel contém todos':''}.`}
function renderAval(a){$('#aAval').textContent=fmt(a.length);$('#aCursos').textContent=fmt(uniq(a,x=>norm(x.capacitacao)));let nums=a.map(x=>Number(x.satisfacao)).filter(Number.isFinite),avg=nums.length?nums.reduce((s,x)=>s+x,0)/nums.length:0,pos=nums.length?100*nums.filter(x=>x>=4).length/nums.length:0;$('#aMedia').textContent=avg?avg.toFixed(2).replace('.',','):'—';$('#aPos').textContent=nums.length?pos.toFixed(1).replace('.',',')+'%':'—';let sat=count(a,x=>x.satisfacao);chart('#chSat','doughnut',Object.keys(sat).sort(),Object.keys(sat).sort().map(k=>sat[k]),'Avaliações');let yes={},tot={};a.forEach(x=>Object.entries(x.respostas||{}).forEach(([k,v])=>{if(/^SIM$/i.test(v||''))yes[k]=(yes[k]||0)+1;if(v)tot[k]=(tot[k]||0)+1}));let qs=Object.keys(yes).slice(0,8), vals=qs.map(k=>tot[k]?100*yes[k]/tot[k]:0);chart('#chQuest','bar',qs.map(x=>x.replace('Você acha que poderá ','').slice(0,45)),vals,'Sim (%)');$('#posComments').innerHTML=a.filter(x=>x.comentario_positivo).slice(0,100).map(x=>`<div class="comment">${esc(x.comentario_positivo)}</div>`).join('')||'<p class="small">Sem comentários para os filtros.</p>';$('#negComments').innerHTML=a.filter(x=>x.ponto_melhoria).slice(0,100).map(x=>`<div class="comment">${esc(x.ponto_melhoria)}</div>`).join('')||'<p class="small">Sem pontos registrados para os filtros.</p>'}
async function png(){let el=$('#capture');let canvas=await html2canvas(el,{scale:1.5,backgroundColor:'#f4f7f9',useCORS:true});let a=document.createElement('a');a.download=`painel-nepe-${S.tab}-${S.year||'todos'}.png`;a.href=canvas.toDataURL('image/png');a.click()}
function xlsx(){let wb=XLSX.utils.book_new();if(S.tab==='avaliacao'){let rows=fav().map(x=>({Ano:x.ano,Capacitação:x.capacitacao,Satisfação:x.satisfacao,'Comentário positivo':x.comentario_positivo||'','Ponto de melhoria':x.ponto_melhoria||'',...(x.respostas||{})}));XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),'Avaliações')}else{let rows=fc().map(x=>({Nome:x.n,Data:x.dt,Ano:x.a,Curso:x.c,'Grupo/base':x.g,'Categoria original':x.cat,Vínculo:x.v,Instituição:x.i,'Processo SEI':x.s}));XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),'Participações');let ce=fcert().map(x=>({Nome:x.n,'Data de emissão':x.dt,Ano:x.a,Categoria:x.g,Vínculo:x.v,Instituição:x.i,'Código do certificado':x.cod}));XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(ce),'Certificados')}XLSX.writeFile(wb,`relatorio-nepe-${S.tab}-${S.year||'todos'}.xlsx`)}
