const COLORS=['#123f72','#2588ee','#184c45','#59a678','#8c8c8c','#f0b44d'];
let all=[], selectedYear='';
const objectiveQuestions=[
'O evento atingiu o seu objetivo?','A carga horária foi bem distribuída?','O programa estabelecido foi desenvolvido?','A abordagem prática foi suficiente?','As instalações e recursos foram adequados?','O material didático da apresentação foi satisfatório?','Você diria que seu aproveitamento nesta capacitação foi bom?','Você acha que poderá aplicar os conhecimentos adquiridos durante o evento, na sua prática profissional?'];
const instructorQuestions=['Clareza e objetividade ao expor o assunto','Habilidade na utilização de métodos e técnicas de ensino','Conhecimento da temática apresentada','Utilização dos recursos didáticos para dinamizar a apresentação','Relacionamento com o grupo'];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function counts(rows,getter){let m={};rows.forEach(r=>{let v=getter(r);if(v!==null&&v!==undefined&&v!=='')m[v]=(m[v]||0)+1});return m}
function donutHTML(map,big=false){let entries=Object.entries(map).sort((a,b)=>b[1]-a[1]), total=entries.reduce((s,x)=>s+x[1],0);if(!total)return '<div class="empty">Sem respostas para o filtro selecionado.</div>';let p=0,stops=[];entries.forEach(([k,v],i)=>{let a=p,b=p+v/total*100;stops.push(`${COLORS[i%COLORS.length]} ${a}% ${b}%`);p=b});let legend=entries.map(([k,v],i)=>`<div><span class="dot" style="background:${COLORS[i%COLORS.length]}"></span>${esc(k)} — <b>${v}</b> (${(v/total*100).toFixed(1).replace('.',',')}%)</div>`).join('');return `<div class="donut-wrap ${big?'big-donut':''}"><div class="donut" style="background:conic-gradient(${stops.join(',')})"></div><div class="legend">${legend}</div></div>`}
function filtered(){let c=document.getElementById('course').value;return all.filter(r=>(!selectedYear||String(r.ano)===String(selectedYear))&&(!c||r.capacitacao===c))}
function renderComments(id,rows,key){let vals=rows.map(r=>r[key]).filter(Boolean);document.getElementById(id).innerHTML=vals.length?vals.map(v=>`<div class="comment">${esc(v)}</div>`).join(''):'<div class="empty">Nenhum comentário para o filtro selecionado.</div>'}
function renderCards(id,questions,rows){document.getElementById(id).innerHTML=questions.map(q=>`<article class="chart-card"><h3>${esc(q)}</h3>${donutHTML(counts(rows,r=>r.respostas[q]))}</article>`).join('')}
function render(){let rows=filtered();document.getElementById('responses').textContent=rows.length.toLocaleString('pt-BR');document.getElementById('actions').textContent=new Set(rows.map(r=>r.capacitacao).filter(Boolean)).size.toLocaleString('pt-BR');let sats=rows.map(r=>r.satisfacao).filter(Number.isFinite);document.getElementById('avg').textContent=sats.length?(sats.reduce((a,b)=>a+b,0)/sats.length).toFixed(2).replace('.',','):'—';document.getElementById('satisfaction').innerHTML=donutHTML(counts(rows,r=>r.satisfacao),true);renderComments('positive',rows,'comentario_positivo');renderComments('negative',rows,'ponto_melhoria');renderCards('questions',objectiveQuestions,rows);renderCards('instructors',instructorQuestions,rows)}
fetch('dados/dados_painel.json').then(r=>{if(!r.ok)throw Error('Falha ao carregar dados');return r.json()}).then(data=>{all=data.registros;document.getElementById('updated').textContent=data.meta.ultima_atualizacao;let courses=[...new Set(all.map(r=>r.capacitacao).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'pt-BR'));document.getElementById('course').insertAdjacentHTML('beforeend',courses.map(c=>`<option>${esc(c)}</option>`).join(''));let years=[...new Set(all.map(r=>r.ano).filter(Boolean))].sort();document.getElementById('years').innerHTML=years.map(y=>`<button data-year="${y}">${y}</button>`).join('');document.querySelectorAll('#years button').forEach(b=>b.onclick=()=>{selectedYear=selectedYear===b.dataset.year?'':b.dataset.year;document.querySelectorAll('#years button').forEach(x=>x.classList.toggle('active',x.dataset.year===selectedYear));render()});render()}).catch(e=>{document.querySelector('main').innerHTML=`<div class="card"><h2>Não foi possível carregar os dados</h2><p>${esc(e.message)}. Abra a aplicação por um servidor web ou pelo GitHub Pages.</p></div>`});
document.getElementById('course').onchange=render;document.getElementById('clear').onclick=()=>{selectedYear='';document.getElementById('course').value='';document.querySelectorAll('#years button').forEach(x=>x.classList.remove('active'));render()};
